#Application

application-name: @artifactId@
application-description: @project.description@
application-version: @project.version@
contact-name: Julián Camilo Vega Rocha
contact-email: ingjulianvega@gmail.com
contact-url: https://twitter.com/ingjulianvega

spring:
  application:
    name: @artifactId@
server:
  port: 9090
  #servlet:
   # context-path: /happy-animals/v1/owner
#Logging
#logging:
#  level:
#    root: DEBUG